# yaml-language-server: $schema=https://raw.githubusercontent.com/snapcore/snapcraft/master/schema/snapcraft.json
name: kase
base: core24
version: "0.2.0"
source-code: https://github.com/raineszm/kase.git
issues: https://github.com/raineszm/kase/issues
contact: dev@zmraines.com
license: MIT

summary: Fuzzy finder for local Salesforce case directories
description: |
  Kase is a fuzzy finder that allows quickly navigating local directories
  corresponding to Salesforce cases. Kase requires a $CASE_REPO directory
  in which all case folders live. These directories should by named according
  to their Salesforce ID (`kase init` automates this process).

  The most useful subcommands are

  - `kase init` - creates a case.json file (and the containing folder if needed)
  - `kase query` - opens the fuzzy finder and returns the selected case
  - `kase shell` - outputs a shell function that allows jumping to cases with
                  the fuzzy finder.
  - `kase import` - import cases from a csv

grade: devel
confinement: strict

apps:
  kase:
    command: bin/kase
    plugs:
      - home

parts:
  kase:
    build-snaps:
      - astral-uv
    plugin: uv
    source: .
